version: "3"
  redis:
    image: redis
    ports:
      - "9200:9200"

  postgres:
    image: portgres
    ports:
      - "5432:5432"

  nginx:
    image: nginx
    ports:
      - "883:80"
    volumes:
      - ./html:/opt/app/

  tomcat:
    build: ./
    ports:
      - "8081:8080"
    links:
      - postgres
      - redis