app:
  datasource:
    main:
      driver-class-name: org.postgres.Driver
      jdbc-url: jdbc:postgresql//localhost:5432/postgres
      password: 'postgres'
      pool-size: 30
      username: postgres

server:
  error:
    incude-binding-errors: always
    incude-message: always
