name: Pipeline NPT

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]

jobs:
  python:
    runs-on: ubuntu-latest
    needs: [ubuntu]
    strategy:
      matrix:
        python-version:
          - 'pypy-3.6'
          - 'pypy-3.7-v7.3.3'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        run: |
          pwd
          ls -la
          docker-compose up -d --force-recreate
